### ISSUE TITLE
Consider using built-in refactors

### ISSUE THREAD

**Issue by sandersn** [CyriacBr/es5-to-dts#3]
Typescript has some built-in refactors that convert JS constructor functions to classes and `require` into modules. You could apply those everywhere throughout a file instead of manually gathering related properties, etc etc.

**Comment by CyriacBr** [comment]
I'm unaware of these functions but I'll take a look, thanks.

**Comment by CyriacBr** [comment]
@sandersn I've been working on a new version of es5-to-dts. Can't seem to find the built-in refactors you're talking about. I'll appreciate some guidance.

I'm trying to implement type guessing, and the fact that the compiler API can't extract symbols from class-like functions requires me to manually check everything. So hopefully these refactors will help greatly.

```javascript
  Math.round(1.5);  // Symbol exists, able to get the type of the call expression.

  function MyClass() {}
  MyClass.prototype.myMethod = function(a) {
    return Math.round(a);
  }
  let c = new MyClass();
  c.myMethod(4); // Symbol is undefined
```

**Comment by CyriacBr** [comment]
@sandersn If you were talking about [this](https://github.com/Microsoft/TypeScript/blob/master/src/services/codefixes/convertFunctionToEs6Class.ts), I'd rather not use it because it can't handle many of my test cases (prototype inheritance, Object.defineProperties, method re-assignments, etc). So for the sake of consistency, I'd rather collect properties by hand.  
Thanks for the suggestion anyway, might come in handy at a later date.
